# Generated by Django 4.2 on 2023-04-27 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portbackend', '0003_alter_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmore',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learnmore',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learnmore',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
