# Generated by Django 4.2 on 2023-04-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portbackend', '0004_learnmore_date_add_learnmore_date_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
